services:
  db:
    image: postgres:16-alpine
    container_name: mystats_db
    restart: always
    environment:
      POSTGRES_USER: yvan
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: mystatsdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: mystats_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"

volumes:
  postgres_data: